language: node_js
node_js:
  - "10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y g++-4.8 g++-4.8-multilib gcc-multilib
  - sudo apt-get install -y libusb-1.0-0-dev
  - sudo apt-get install -y libudev-dev